
spring:
  application:
    name: bus-auth-service
  zipkin:
    base-url: http://zipkin-server:9411
    
  datasource:
    url: jdbc:postgresql://businventory.cikvtti1fhkz.us-east-2.rds.amazonaws.com:5432/booking
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true      # Print SQL queries to console for debugging
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    
eureka:
  client:
    service-url:
      defaultZone: http://bus-eureka-server:8070/eureka
      
server:
  port: 8077
  servlet:
    context-path: /auth

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true