
spring:
  application:
    name: bus-booking-service
  zipkin:
    base-url: http://zipkin-server:9411
    
  datasource:
    url: jdbc:postgresql://businventory.cikvtti1fhkz.us-east-2.rds.amazonaws.com:5432/booking
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true      # Print SQL queries to console for debugging
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  activemq:
    broker-url: tcp://activemq:61616
    
eureka:
  client:
    service-url:
      defaultZone: http://bus-eureka-server:8070/eureka
      
server:
  port: 8074
  servlet:
    context-path: /booking


endpoint:
  inventory:
    host: http://BUS-INVENTORY-SERVICE/inventory
    getInventories: /api/v1/buses/{bus_id}/inventories
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
